[package]
name = "kahea-ingest"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kahea-core = { path = "../kahea-core" }
serde_json.workspace = true
shell-words.workspace = true
thiserror.workspace = true
url.workspace = true
yaml-rust2.workspace = true
